import type { Metadata } from 'next'
import './globals.css'
import NextAuthSessionProvider from '@/providers/SessionProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body className={'bg-zinc-950 text-zinc-50 antialiased'}>
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  )
}
